### ISSUE TITLE
Some selftests don't build with GCC9 due to r1 clobber

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#256]
eg:

```
ptrace-tm-tar.c: In function 'tm_tar':
ptrace-tm-tar.c:29:2: error: listing the stack pointer register 'r1' in a clobber list is deprecated [-Werror=deprecated]
   29 |  asm __volatile__(
      |  ^~~
ptrace-tm-tar.c:29:2: note: the value of the stack pointer after an 'asm' statement must be the same as it was before the statement
```

**Comment by shenki** [comment]
mpe fixed this in https://github.com/torvalds/linux/commit/a02cbc7ffe529ed58b6bbe54652104fc2c88bd77

To confirm, the ptrace-tm-tar test appears to build with GCC 10 (10.0.2-3 from Debian).
