### ISSUE TITLE
Fix build break with CMA=n && SPAPR_TCE_IOMMU=y

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#75]
A config with `CMA=n` (which requires disabling KVM), and `SPAPR_TCE_IOMMU=y` breaks as follows:

```
  arch/powerpc/mm/mmu_context_iommu.c: In function ‘mm_iommu_get’:
  arch/powerpc/mm/mmu_context_iommu.c:193:42: error: ‘MIGRATE_CMA’ undeclared (first use in this function)
  if (get_pageblock_migratetype(page) == MIGRATE_CMA) {
  ^~~~~~~~~~~
  arch/powerpc/mm/mmu_context_iommu.c:193:42: note: each undeclared identifier is reported only once for each function it appears in
  make[2]: *** [arch/powerpc/mm/mmu_context_iommu.o] Error 1
```

Caused by commit 2e5bbb5461f1.
