### ISSUE TITLE
Build break when CRASH_DUMP=n and POWERNV=y

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#117]
```
arch/powerpc/platforms/powernv/smp.c: In function 'pnv_smp_cpu_kill_self':
arch/powerpc/platforms/powernv/smp.c:236:4: error: implicit declaration of function 'crash_ipi_callback'
    crash_ipi_callback(&regs);
    ^~~~~~~~~~~~~~~~~~
```

Caused by 4145f358644b ("powernv/kdump: Fix cases where the kdump kernel can get HMI's")
