### ISSUE TITLE
SPLPAR=n build is broken

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#116]
```
arch/powerpc/platforms/pseries/hotplug-cpu.o: In function `.dlpar_online_cpu':
hotplug-cpu.c:(.text+0xc40): undefined reference to `.find_and_online_cpu_nid'
```

http://kisskb.ellerman.id.au/kisskb/buildresult/13272276/

Caused by e67e02a544e9 ("powerpc/pseries: Fix cpu hotplug crash with memoryless nodes").
